@php
$navbar = \App\Models\University::find($university->id??$id);
@endphp
<div class="col-md-4 col-xs-12 pl-0 order-md-last order-first">
    <ul class="cv-list">
        <li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id])}}" @if(($class ?? '') == 'view') class="color-C11800" @endif > @if(($class ?? '') == 'view') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif @if($name == 'universities') О ВУЗе @else О колледже @endif </a></li>
        @if($navbar->achievements)<li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id, 1])}}" @if(($class ?? '') == 'achieve') class="color-C11800" @endif  > @if(($class ?? '') == 'achieve') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Достижения</a></li>@endif
        @if($navbar->coop)<li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id, 2])}}" @if(($class ?? '') == 'coop') class="color-C11800" @endif  > @if(($class ?? '') == 'coop') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Сотрудничество</a></li>@endif
        @if($navbar->rating)<li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id, 3])}}" @if(($class ?? '') == 'rating') class="color-C11800" @endif  > @if(($class ?? '') == 'rating') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Рейтинг</a></li>@endif
        @if($navbar->grants)<li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id, 4])}}" @if(($class ?? '') == 'discounts') class="color-C11800" @endif  > @if(($class ?? '') == 'discounts') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Гранты / Скидки</a></li>@endif
        @if($navbar->learn_program)<li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id, 5])}}"  @if(($class ?? '') == 'edu') class="color-C11800" @endif  > @if(($class ?? '') == 'edu') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Образовательные программы</a></li>@endif
        @if($navbar->docs_income)<li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id, 6])}}"  @if(($class ?? '') == 'docs') class="color-C11800" @endif  > @if(($class ?? '') == 'docs') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Документы для поступления</a></li>@endif
        @if($navbar->short_description)<li><a href="{{url('qazaqstan/navigator/list/'.$name.'/view', [$university->id??$id, 7])}}"  @if(($class ?? '') == 'contacts') class="color-C11800" @endif  > @if(($class ?? '') == 'contacts') <img src="{{asset('img/arrow-dots-red.svg')}}" alt=""> @else <img src="{{asset('img/arrow-dots-black.svg')}}" alt=""> @endif Контакты</a></li>@endif
    </ul>
</div>
